config/routes.rb
FootballBetting::Application.routes.draw do
  
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!
  
  def index    
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<style type="text/css">
// Place all the styles related to the home controller here.
// They will automatically be included in application.css.
// You can use Sass (SCSS) here: http://sass-lang.com/
*{
	margin:0;
	padding:0;
}
body{
	font-family:Helvetica, sans-serif;
	font-size:16px;
	color:#fff;
	/*background-color:#000;*/
	overflow:hidden;
}
h1{
	margin:20px;
	font-size:40px;
}
.st_overlay{
	width:100%;
	height:100%;
	position:fixed;
	top:0px;
	left:0px;
	background:transparent url(../assets/pattern.png) repeat-x bottom left;
	opacity:0.3;
}
.st_main img.st_preview{
	position:absolute;
	left:0px;
	top:0px;
	width:100%;
}
ul.st_navigation{
	position:absolute;
	width:100%;
	top:140px;
	left:-300px;
	list-style:none;
}
ul.st_navigation li {
	float:left;
	clear:both;
	margin-bottom:8px;
	position:relative;
	width:100%;
}
ul.st_navigation li span.st_link{
	background-color:#000;
	float:left;
	position:relative;
	line-height:50px;
	padding:0px 20px;
	-moz-box-shadow:0px 0px 2px #000;
	-webkit-box-shadow:0px 0px 2px #000;
	box-shadow:0px 0px 2px #000;
}
ul.st_navigation li span.st_arrow_down,
ul.st_navigation li span.st_arrow_up{
	position:absolute;
	margin-left:15px;
	width:40px;
	height:50px;
	cursor:pointer;
	-moz-box-shadow:0px 0px 2px #000;
	-webkit-box-shadow:0px 0px 2px #000;
	box-shadow:0px 0px 2px #000;
}
ul.st_navigation li span.st_arrow_down{
	background:#000 url(../assets/icons/down.png) no-repeat center center;
}
ul.st_navigation li span.st_arrow_up{
	background:#000 url(../assets/icons/up.png) no-repeat center center;
}
.st_wrapper{
	display:none;
	position: absolute;
    width:100%;
    height:126px;
    overflow-y:hidden;
	top:50px;
    left:0px;
}
.st_thumbs{
    height:126px;
    margin: 0;
}
.st_thumbs img{
    float:left;
    margin:3px 3px 0px 0px;
    cursor:pointer;
	-moz-box-shadow:1px 1px 5px #000;
	-webkit-box-shadow:1px 1px 5px #000;
	box-shadow:1px 1px 5px #000;
	opacity:0.7;
	filter:progid:DXImageTransform.Microsoft.Alpha(opacity=70);
}
.st_loading{
	position:fixed;
	top:10px;
	right:0px;
	background:#000 url(../assets/icons/loader.gif) no-repeat 10px 50%;
	padding:15px 40px 15px 60px;
	-moz-box-shadow:0px 0px 2px #000;
	-webkit-box-shadow:0px 0px 2px #000;
	box-shadow:0px 0px 2px #000;
	opacity:0.6;
	filter:progid:DXImageTransform.Microsoft.Alpha(opacity=60);
}
.st_about{
	display:none;
	position:absolute;
	top:50px;
    left:0px;
	opacity:0.6;
	filter:progid:DXImageTransform.Microsoft.Alpha(opacity=60);
}
.st_subcontent{
	background:#000;
	padding:30px;
	-moz-box-shadow:0px 0px 10px #000;
	-webkit-box-shadow:0px 0px 10px #000;
	box-shadow:0px 0px 10px #000;
}	
</style>

<center><h3>Vertical Photo Viewer</h3></center>
<center><small>This is not a complete task but it's a proof of concept</small></center>




<div id="st_main" class="st_main">
	<img src="assets/album/1.jpg" alt="" class="st_preview" style="display:none;"/>
	<div class="st_overlay"></div>
	<h1>Mark Sebastian</h1>
	<div id="st_loading" class="st_loading"><span>Loading...</span></div>
	<ul id="st_nav" class="st_navigation">
		<li class="album">
			<span class="st_link">Newest Collection<span class="st_arrow_down"></span></span>
			<div class="st_wrapper st_thumbs_wrapper">
				<div class="st_thumbs">
					<img src="assets/album/thumbs/1.jpg" alt="assets/album/1.jpg"/>
					<img src="assets/album/thumbs/2.jpg" alt="assets/album/2.jpg"/>
					<img src="assets/album/thumbs/3.jpg" alt="assets/album/3.jpg"/>
					<img src="assets/album/thumbs/4.jpg" alt="assets/album/4.jpg"/>
					<img src="assets/album/thumbs/1.jpg" alt="assets/album/1.jpg"/>
					<img src="assets/album/thumbs/2.jpg" alt="assets/album/2.jpg"/>
					<img src="assets/album/thumbs/3.jpg" alt="assets/album/3.jpg"/>
					<img src="assets/album/thumbs/4.jpg" alt="assets/album/4.jpg"/>
					<img src="assets/album/thumbs/1.jpg" alt="assets/album/1.jpg"/>
					<img src="assets/album/thumbs/2.jpg" alt="assets/album/2.jpg"/>
					<img src="assets/album/thumbs/3.jpg" alt="assets/album/3.jpg"/>
					<img src="assets/album/thumbs/4.jpg" alt="assets/album/4.jpg"/>
				</div>
			</div>
		</li>
		<li class="album">
			<span class="st_link">Random Photography<span class="st_arrow_down"></span></span>
			<div class="st_wrapper st_thumbs_wrapper">
				<div class="st_thumbs">
					<img src="assets/album/thumbs/1.jpg" alt="assets/album/1.jpg"/>
					<img src="assets/album/thumbs/2.jpg" alt="assets/album/2.jpg"/>
					<img src="assets/album/thumbs/3.jpg" alt="assets/album/3.jpg"/>
					<img src="assets/album/thumbs/4.jpg" alt="assets/album/4.jpg"/>
					<img src="assets/album/thumbs/1.jpg" alt="assets/album/1.jpg"/>
					<img src="assets/album/thumbs/2.jpg" alt="assets/album/2.jpg"/>
					<img src="assets/album/thumbs/3.jpg" alt="assets/album/3.jpg"/>
					<img src="assets/album/thumbs/4.jpg" alt="assets/album/4.jpg"/>
					<img src="assets/album/thumbs/1.jpg" alt="assets/album/1.jpg"/>
					<img src="assets/album/thumbs/2.jpg" alt="assets/album/2.jpg"/>
					<img src="assets/album/thumbs/3.jpg" alt="assets/album/3.jpg"/>
					<img src="assets/album/thumbs/4.jpg" alt="assets/album/4.jpg"/>
				</div>
			</div>
		</li>
		<li class="album">
			<span class="st_link">Best Shots<span class="st_arrow_down"></span></span>
			<div class="st_wrapper st_thumbs_wrapper">
				<div class="st_thumbs">
					<img src="assets/album/thumbs/1.jpg" alt="assets/album/1.jpg"/>
					<img src="assets/album/thumbs/2.jpg" alt="assets/album/2.jpg"/>
					<img src="assets/album/thumbs/3.jpg" alt="assets/album/3.jpg"/>
					<img src="assets/album/thumbs/4.jpg" alt="assets/album/4.jpg"/>
					<img src="assets/album/thumbs/1.jpg" alt="assets/album/1.jpg"/>
					<img src="assets/album/thumbs/2.jpg" alt="assets/album/2.jpg"/>
					<img src="assets/album/thumbs/3.jpg" alt="assets/album/3.jpg"/>
					<img src="assets/album/thumbs/4.jpg" alt="assets/album/4.jpg"/>
					<img src="assets/album/thumbs/1.jpg" alt="assets/album/1.jpg"/>
					<img src="assets/album/thumbs/2.jpg" alt="assets/album/2.jpg"/>
					<img src="assets/album/thumbs/3.jpg" alt="assets/album/3.jpg"/>
					<img src="assets/album/thumbs/4.jpg" alt="assets/album/4.jpg"/>
				</div>
			</div>
		</li>
		<li class="album">
			<span class="st_link">Award Winning Collection<span class="st_arrow_down"></span></span>
			<div class="st_wrapper st_thumbs_wrapper">
				<div class="st_thumbs">
					<img src="assets/album/thumbs/1.jpg" alt="assets/album/1.jpg"/>
					<img src="assets/album/thumbs/2.jpg" alt="assets/album/2.jpg"/>
					<img src="assets/album/thumbs/3.jpg" alt="assets/album/3.jpg"/>
					<img src="assets/album/thumbs/4.jpg" alt="assets/album/4.jpg"/>
					<img src="assets/album/thumbs/1.jpg" alt="assets/album/1.jpg"/>
					<img src="assets/album/thumbs/2.jpg" alt="assets/album/2.jpg"/>
					<img src="assets/album/thumbs/3.jpg" alt="assets/album/3.jpg"/>
					<img src="assets/album/thumbs/4.jpg" alt="assets/album/4.jpg"/>
					<img src="assets/album/thumbs/1.jpg" alt="assets/album/1.jpg"/>
					<img src="assets/album/thumbs/2.jpg" alt="assets/album/2.jpg"/>
					<img src="assets/album/thumbs/3.jpg" alt="assets/album/3.jpg"/>
					<img src="assets/album/thumbs/4.jpg" alt="assets/album/4.jpg"/>
				</div>
			</div>
		</li>
		<li>
			<span class="st_link">About<span class="st_arrow_down"></span></span>
			<div class="st_about st_thumbs_wrapper">
				<div class="st_subcontent">
					<p>
						I am alone, and feel the charm of existence in this spot,
						which was created for the bliss of souls like mine. I am
						so happy, my dear friend, so absorbed in the exquisite sense
						of mere tranquil existence, that I neglect my talents.
					</p>
				</div>
			</div>
		</li>
	</ul>
</div>


<script type="text/javascript">
$(function() {
	//the loading image
	var $loader		= $('#st_loading');
	//the ul element 
	var $list		= $('#st_nav');
	//the current image being shown
	var $currImage 	= $('#st_main').children('img:first');
	
	//let's load the current image 
	//and just then display the navigation menu
	$('<img>').load(function(){
		$loader.hide();
		$currImage.fadeIn(3000);
		//slide out the menu
		setTimeout(function(){
			$list.animate({'left':'0px'},500);
		},
		1000);
	}).attr('src',$currImage.attr('src'));
	
	//calculates the width of the div element 
	//where the thumbs are going to be displayed
	buildThumbs();
	
	function buildThumbs(){
		$list.children('li.album').each(function(){
			var $elem 			= $(this);
			var $thumbs_wrapper = $elem.find('.st_thumbs_wrapper');
			var $thumbs 		= $thumbs_wrapper.children(':first');
			//each thumb has 180px and we add 3 of margin
			var finalW 			= $thumbs.find('img').length * 183;
			$thumbs.css('width',finalW + 'px');
			//make this element scrollable
			makeScrollable($thumbs_wrapper,$thumbs);
		});
	}
	
	//clicking on the menu items (up and down arrow)
	//makes the thumbs div appear, and hides the current 
	//opened menu (if any)
	$list.find('.st_arrow_down').on('click',function(){
		var $this = $(this);
		hideThumbs();
		$this.addClass('st_arrow_up').removeClass('st_arrow_down');
		var $elem = $this.closest('li');
		$elem.addClass('current').animate({'height':'170px'},200);
		var $thumbs_wrapper = $this.parent().next();
		$thumbs_wrapper.show(200);
	});
	$list.find('.st_arrow_up').on('click',function(){
		var $this = $(this);
		$this.addClass('st_arrow_down').removeClass('st_arrow_up');
		hideThumbs();
	});
	
	//clicking on a thumb, replaces the large image
	$list.find('.st_thumbs img').bind('click',function(){
		var $this = $(this);
		$loader.show();
		$('<img class="st_preview"/>').load(function(){
			var $this = $(this);
			var $currImage = $('#st_main').children('img:first');
			$this.insertBefore($currImage);
			$loader.hide();
			$currImage.fadeOut(2000,function(){
				$(this).remove();
			});
		}).attr('src',$this.attr('alt'));
	}).bind('mouseenter',function(){
		$(this).stop().animate({'opacity':'1'});
	}).bind('mouseleave',function(){
		$(this).stop().animate({'opacity':'0.7'});
	});
	
	//function to hide the current opened menu
	function hideThumbs(){
		$list.find('li.current')
			 .animate({'height':'50px'},400,function(){
				$(this).removeClass('current');
			 })
			 .find('.st_thumbs_wrapper')
			 .hide(200)
			 .andSelf()
			 .find('.st_link span')
			 .addClass('st_arrow_down')
			 .removeClass('st_arrow_up');
	}

	//makes the thumbs div scrollable
	//on mouse move the div scrolls automatically
	function makeScrollable($outer, $inner){
		var extra 			= 800;
		//Get menu width
		var divWidth = $outer.width();
		//Remove scrollbars
		$outer.css({
			overflow: 'hidden'
		});
		//Find last image in container
		var lastElem = $inner.find('img:last');
		$outer.scrollLeft(0);
		//When user move mouse over menu
		$outer.unbind('mousemove').bind('mousemove',function(e){
			var containerWidth = lastElem[0].offsetLeft + lastElem.outerWidth() + 2*extra;
			var left = (e.pageX - $outer.offset().left) * (containerWidth-divWidth) / divWidth - extra;
			$outer.scrollLeft(left);
		});
	}
});	
</script>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Showzee", root_path, :class => 'brand' %>

<% if user_signed_in? %>

	<ul class="nav pull-right">
	  <li class="divider-vertical"></li>
	  <li class="dropdown">
	    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin <b class="caret"></b></a>
	    <ul class="dropdown-menu">
	      <li>
	  	    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
	      </li>
		  <li class="divider"></li>
	      <li>
	  	    <%= link_to 'Edit account', edit_user_registration_path %>
	      </li>
	      <% if current_user.has_role? :admin %>
	        <li>
	  	      <%= link_to 'Privileges', users_path %>
	        </li>	  
	      <% end %>
	    </ul>
	  </li>
	</ul>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "www.showzee.com" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "www.showzee.com" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    <div id="main" role="main">
      <div class="container">
        <!-- <div class="content"> -->
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        <!-- </div> -->
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h3>Users</h3>
<div class="span8">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Registered</th>
      <th>Role</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.to_date %></td>
      <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
      <td>
        <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
        <%= render user %>
      </td>
      <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>